### PR TITLE
Add some dotfiles

### PR DESCRIPTION
**Pull request by lucasmichot**
Add some dotfiles

### CODE REVIEW

**Comment by mathiasgrimm** [comment]
Thanks!
The .editorconfig file is really good idea, though the .gitattributes I would not add as sometimes the files are needed.

**Comment by mathiasgrimm** [comment]
Can you remove the .gitattributes and submit the PR again?

**Comment by lucasmichot** [comment]
You want to export tests and other files in the archive ???

**Comment by mathiasgrimm** [comment]
Yes

**Pull request closed without merging**
